name: Pulumi
author: Pulumi
description: Pulumi's GitHub Actions deploy apps and infrastructure to your cloud of choice, using just your favorite language and GitHub.
branding:
  icon: upload-cloud
  color: purple
inputs:
    command:
        description: 'Pulumi command to run, eg. up'
        required: true
    stack-name:
        description: 'Which stack you want to apply to, eg. dev'
        required: true
runs:
    using: 'node12'
    main: 'dist/index.js'
