name: 'Pulumi CLI Action'
author: Pulumi
description: Pulumi's GitHub Actions deploy apps and infrastructure to your cloud of choice, using just your favorite language and GitHub.
branding:
  icon: upload-cloud
  color: purple
inputs:
  command:
    description: 'Pulumi command to run, eg. up'
    required: true
  stack-name:
    description: 'Which stack you want to apply to, eg. dev'
    required: true
  work-dir:
    description: 'Location of your Pulumi files. Defaults to ./'
    required: false
    default: ./
  comment-on-pr:
    description: 'If true, a comment will be created with results'
    required: false
    default: 'false'
  github-token:
    description: 'Github Token (required to comment on pull requests)'
    required: false
    default: ''
  cloud-url:
    description: 'A cloud URL to log in to'
    required: false
    default: ''
  parallel:
    description: 'Allow P resource operations to run in parallel at once (1 for no parallelism). Defaults to unbounded.'
    required: false
    default: '2147483647'
  message:
    description: 'Optional message to associate with the update operation'
    required: false
    default: ''
  expect-no-changes:
    description: 'Return an error if any changes occur during this update'
    required: false
  diff:
    description: 'Display operation as a rich diff showing the overall change'
    required: false
  replace:
    description: 'Specify resources to replace. Multiple resources can be specified one per line'
    required: false
  target:
    description: 'Specify a single resource URN to update. Other resources will not be updated. Multiple resources can be specified one per line'
    required: false
  target-dependents:
    description: 'Allows updating of dependent targets discovered but not specified in target.'
    required: false
    default: 'false'
outputs:
  output:
    description: Output from running command
runs:
  using: 'node12'
  main: 'dist/index.js'
