name: Pulumi
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Installing dependencies 📦️
        run: yarn install

      - name: Authenticate with Google 🔑
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Applying infrastructure 🚀
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          cloud-url: gs://my-bucket-name
        env:
          # You can elide PULUMI_CONFIG_PASSPHRASE below if you're using Google KMS
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
