name: "Publish Immutable Action Version"

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Publish
        id: publish
        uses: actions/publish-immutable-action@v0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
