name: 'test-output'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  test-output: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
        with:
          pulumi-version: 2.16.2
      - run: |
          pulumi login --local
          pulumi stack init dev
        working-directory: .github/test-stacks/golang
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
      - uses: ./
        if: always()
        id: pulumi
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: up
          cloud-url: file://~
          stack-name: dev
          work-dir: .github/test-stacks/golang
      - run: echo "My pet name is ${{ steps.pulumi.outputs.pet-name }}"
      - run: echo "Pulumi had to say this, ${{ steps.pulumi.outputs.output }}"
