name: 'Application with Extra Options'
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test-workflow:
    runs-on: ${{ matrix.os }}
    name: Testing Pulumi ${{ matrix.command }} on ${{ matrix.os }}
    strategy:
      matrix:
        command: [ up, refresh, destroy, preview ]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Create local stack
        run: |
          pulumi login --local
          pulumi stack init dev
        working-directory: .github/test-stacks/nodejs
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
      - run: npm install
        working-directory: .github/test-stacks/nodejs
      - uses: ./
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: ${{ matrix.command }}
          cloud-url: file://~
          stack-name: dev
          work-dir: .github/test-stacks/nodejs
          parallel: 3
          message: this-is-just-a-test
          expect-no-changes: false
          diff: true
